### ISSUE TITLE
Need Hidetext helper class

### ISSUE THREAD

**Issue by davidhemphill** [davidhemphill/beard#3]
Something like this would do:

```scss
.hidetext {
    text-indent: 100%;
    white-space: nowrap;
    overflow: hidden;
}
```
