### ISSUE TITLE
Need responsive hide classes

### ISSUE THREAD

**Issue by davidhemphill** [davidhemphill/beard#4]
Should use all the registered breakpoints and output something like this:

```scss
.sm-hide {
    @include media($only-sm) {
        display: none;
    }
}
```
