### ISSUE TITLE
Add default active class helper

### ISSUE THREAD

**Issue by davidhemphill** [davidhemphill/beard#6]
Something that outputs something like this: 

```scss
.default-active {
    &:active {
        opacity: 0.5;
    }
}
```
